Repository aws/amazon-sagemaker-examples, pull requests merged in 2020-11, with the labels that each got.

#1640 added autogluon v0.0.14 support, changed the build method
  advanced_functionality/autogluon-tabular/AutoGluon_Tabular_SageMaker.ipynb
  advanced_functionality/autogluon-tabular/container-inference/Dockerfile.inference
  advanced_functionality/autogluon-tabular/container-training/Dockerfile.training
  advanced_functionality/autogluon-tabular/container-training/inference.py
  advanced_functionality/autogluon-tabular/container-training/train.py
Labels: status: awaiting response

#1602 added data ingestion notebooks
  data_ingestion/011_Ingest_tabular_data_v1.ipynb
  data_ingestion/012_Ingest_text_data_v2.ipynb
  data_ingestion/013_Ingest_image_data_v1.ipynb
  data_ingestion/02_Ingest_data_with_Athena_v1.ipynb
  data_ingestion/03_Ingest_data_with_Redshift_v3.ipynb
  data_ingestion/04_Ingest_data_with_EMR.ipynb
  data_ingestion/image/athena-iam-1.png
  data_ingestion/image/athena-iam-2.PNG
  data_ingestion/image/athena-iam-3.PNG
  data_ingestion/image/redshift-sg-1.PNG
  data_ingestion/image/redshift-sg-1.jpg
  preprocessing/text_data/04_preprocessing_text_data_v3.ipynb
Labels: status: blocked

#1675 Sample notebook fix 2
  hyperparameter_tuning/mxnet_gluon_cifar10_random_search/hyperparameter_tuning_mxnet_gluon_cifar10_random_search.ipynb
Labels: status: blocked

#1638 Updated Neo compilation notebook for GluonCV Yolo example
  sagemaker_neo_compilation_jobs/gluoncv_yolo_darknet/gluoncv_yolo_darknet_neo.ipynb
  sagemaker_neo_compilation_jobs/gluoncv_yolo_darknet/train_yolo.py
Labels: status: blocked

#1628 Fixed malformed TensorFlow estimator declaration.
  aws_sagemaker_studio/frameworks/tensorflow_mnist/tensorflow_mnist.ipynb
Labels: status: blocked

#1265 logx=False plots data as User_Score is <=10
  introduction_to_applying_machine_learning/video_game_sales/video-game-sales-xgboost.ipynb
Labels: status: blocked

#1656 fix: mnist notebook for neo tensorflow
  sagemaker_neo_compilation_jobs/tensorflow_distributed_mnist/mnist.py
  sagemaker_neo_compilation_jobs/tensorflow_distributed_mnist/tensorflow_distributed_mnist_neo.ipynb
Labels: status: awaiting response

#1047 Enable S3 Endpoint URL configuration
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/evaluation_worker.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/metrics/constants.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/metrics/s3_metrics.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/rollout_worker.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/checkpoint.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/checkpoint_files/deepracer_checkpoint_json.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/checkpoint_files/rl_coach_checkpoint.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/checkpoint_files/rl_coach_sync_file.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/checkpoint_files/tensorflow_model.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/hyperparameters.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/ip_config.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/metrics.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/model_metadata.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/reward_function.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/simtrace_video.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/files/yaml_file.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/s3/s3_client.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/samples/sample_collector.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/tournament_worker.py
  reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/markov/training_worker.py
Labels: status: awaiting response

#1605 Add first 2 guides for image data
  image_data_guide/01_download_data.ipynb
  image_data_guide/02_structuring_data.ipynb
  image_data_guide/03a_builtin_preprocessing.ipynb
  image_data_guide/03b_tensorflow_preprocessing.ipynb
  image_data_guide/03c_pytorch_preprocessing.ipynb
  image_data_guide/04a_builtin_training.ipynb
  image_data_guide/04b_tensorflow_training.ipynb
  image_data_guide/04c_pytorch_training.ipynb
  image_data_guide/training_pytorch/pytorch_train.py
  image_data_guide/training_tensorflow/requirements.txt
  image_data_guide/training_tensorflow/tensorflow_train.py
Labels: status: awaiting response

#1629 Updated scikit_learn_iris example to be compatible with SageMaker SDK 2.x
  sagemaker-python-sdk/scikit_learn_iris/scikit_learn_estimator_example_with_batch_transform.ipynb
Labels: status: awaiting response

#1674 Update semantic segmentation algorithm example
  introduction_to_amazon_algorithms/semantic_segmentation_pascalvoc/.gitignore
  introduction_to_amazon_algorithms/semantic_segmentation_pascalvoc/semantic_segmentation_pascalvoc.ipynb
Labels: status: in progress

#1717 Notebook fixed and cleaned - Factorization Machine
  introduction_to_amazon_algorithms/factorization_machines_mnist/factorization_machines_mnist.ipynb
Labels: status: blocked

#1710 Notebook formatted and fixed error due to syntax change
  sagemaker-python-sdk/1P_kmeans_highlevel/kmeans_mnist.ipynb
Labels: status: awaiting response

#1718 Notebook fixed and cleaned - random cut forest
  introduction_to_amazon_algorithms/random_cut_forest/random_cut_forest.ipynb
Labels: status: blocked

#1714 Errors fixed and notebook cleaned - DeepAR synthetic
  introduction_to_amazon_algorithms/deepar_synthetic/deepar_synthetic.ipynb
Labels: status: awaiting response

#1690 fix issues byo algo with pipe mode example
  advanced_functionality/pipe_bring_your_own/Dockerfile
  advanced_functionality/pipe_bring_your_own/pipe_bring_your_own.ipynb
Labels: status: pending

#1655 Added serving, improved automated testing, refactored backend
  hyperparameter_tuning/rapids_bring_your_own/code/Dockerfile
  hyperparameter_tuning/rapids_bring_your_own/code/HPOConfig.py
  hyperparameter_tuning/rapids_bring_your_own/code/HPODatasets.py
  hyperparameter_tuning/rapids_bring_your_own/code/MLWorkflow.py
  hyperparameter_tuning/rapids_bring_your_own/code/entrypoint.sh
  hyperparameter_tuning/rapids_bring_your_own/code/rapids_cloud_ml.py
  hyperparameter_tuning/rapids_bring_your_own/code/serve.py
  hyperparameter_tuning/rapids_bring_your_own/code/train.py
  hyperparameter_tuning/rapids_bring_your_own/code/workflows/MLWorkflowMultiCPU.py
  hyperparameter_tuning/rapids_bring_your_own/code/workflows/MLWorkflowMultiGPU.py
  hyperparameter_tuning/rapids_bring_your_own/code/workflows/MLWorkflowSingleCPU.py
  hyperparameter_tuning/rapids_bring_your_own/code/workflows/MLWorkflowSingleGPU.py
  hyperparameter_tuning/rapids_bring_your_own/helper_functions.py
  hyperparameter_tuning/rapids_bring_your_own/img/rapids_hpo.png
  hyperparameter_tuning/rapids_bring_your_own/rapids_sagemaker_hpo.ipynb
Labels: status: awaiting response

#1803 Updated xgboost_customer_churn.ipynb for SageMaker SDK v2
  introduction_to_applying_machine_learning/xgboost_customer_churn/xgboost_customer_churn.ipynb
Labels: status: awaiting response
