Repository aws/amazon-sagemaker-examples, pull requests merged in 2021-03, with the labels that each got.

#1947 Added example for SageMaker Debugger XGBoost Training Report
  sagemaker-debugger/xgboost_training_report/higgs_boson_detection.ipynb
Labels: status: awaiting response

#1888 Add Mxnet MNIST example
  frameworks/mxnet/code/config.json
  frameworks/mxnet/code/inference.py
  frameworks/mxnet/code/test_inference.py
  frameworks/mxnet/code/test_train.py
  frameworks/mxnet/code/train.py
  frameworks/mxnet/get_started_mnist_deploy.ipynb
  frameworks/mxnet/get_started_mnist_train.ipynb
Labels: status: awaiting response

#2083 Bump tensorflow patch versions
  frameworks/tensorflow/get_started_mnist_deploy.ipynb
  frameworks/tensorflow/get_started_mnist_train.ipynb
  hyperparameter_tuning/tensorflow2_mnist/hpo_tensorflow2_mnist.ipynb
  prep_data/image_data_guide/03b_tensorflow_preprocessing.ipynb
Labels: priority: high

#2034 Update mxnet eia notebook examples
  sagemaker-python-sdk/mxnet_mnist/mnist_ei.py
  sagemaker-python-sdk/mxnet_mnist/mxnet_mnist_elastic_inference.ipynb
  sagemaker-python-sdk/mxnet_mnist/mxnet_mnist_elastic_inference_local.ipynb
Labels: status: blocked by CI
