Repository aws/amazon-sagemaker-examples, pull requests merged in 2021-05, with the labels that each got.

#1912 RL: Update Dockerfile for roboschool stable baselines
  reinforcement_learning/rl_roboschool_stable_baselines/Dockerfile
  reinforcement_learning/rl_roboschool_stable_baselines/rl_roboschool_stable_baselines.ipynb
Labels: status: pending

#2174 [Website] Debugger notebook updates
  index.rst
  sagemaker-debugger/debugger_interactive_analysis_profiling/interactive_analysis_profiling_data.ipynb
  sagemaker-debugger/index.rst
  sagemaker-debugger/model_specific_realtime_analysis/autoencoder_mnist/autoencoder_mnist.ipynb
  sagemaker-debugger/model_specific_realtime_analysis/bert_attention_head_view/bert_attention_head_view.ipynb
  sagemaker-debugger/model_specific_realtime_analysis/cnn_class_activation_maps/cnn_class_activation_maps.ipynb
  sagemaker-debugger/tensorflow_nlp_sentiment_analysis/sentiment-analysis-tf-distributed-training-bringyourownscript.ipynb
  sagemaker-debugger/tensorflow_profiling/callback_bottleneck.ipynb
  sagemaker-debugger/tensorflow_profiling/low_batch_size.ipynb
  sagemaker-debugger/xgboost_training_report/higgs_boson_detection.ipynb
Labels: type: documentation

#2598 infra: format .py and .ipynb files with black
  hyperparameter_tuning/tensorflow_mnist/hpo_tensorflow_mnist.ipynb
  introduction_to_applying_machine_learning/US-census_population_segmentation_PCA_Kmeans/sagemaker-countycensusclustering.ipynb
  sagemaker-debugger/pytorch_model_debugging/pytorch_script_change_smdebug.ipynb
  sagemaker-debugger/pytorch_model_debugging/scripts/pytorch_mnist.py
  sagemaker-debugger/tensorflow_nlp_sentiment_analysis/sentiment-analysis-tf-distributed-training-bringyourownscript.ipynb
  sagemaker-featurestore/feature_store_client_side_encryption.ipynb
  sagemaker-script-mode/my_custom_library/__init__.py
  sagemaker-script-mode/pytorch_script/train_deploy_pytorch_without_dependencies.py
  sagemaker-script-mode/sagemaker-script-mode.ipynb
  sagemaker-script-mode/scikitlearn_script/train_deploy_scikitlearn_without_dependencies.py
  sagemaker-script-mode/xgboost_script/train_deploy_xgboost_with_dependencies.py
  sagemaker-spark/pyspark_mnist/pyspark_mnist_kmeans.ipynb
  sagemaker-spark/pyspark_mnist/pyspark_mnist_pca_kmeans.ipynb
  sagemaker-spark/pyspark_mnist/pyspark_mnist_pca_mllib_kmeans.ipynb
  sagemaker-spark/pyspark_mnist/pyspark_mnist_xgboost.ipynb
  sagemaker_batch_transform/batch_transform_associate_predictions_with_input/Batch Transform - breast cancer prediction with high level SDK.ipynb
  sagemaker_batch_transform/batch_transform_associate_predictions_with_input/Batch Transform - breast cancer prediction with lowel level SDK.ipynb
  sagemaker_neo_compilation_jobs/tensorflow_unet/sagemaker-neo-tf-unet.ipynb
  scientific_details_of_algorithms/lda_topic_modeling/generate_example_data.py
  training/distributed_training/mpi_on_sagemaker/intro/mpi_demo.py
Labels: priority: low, type: maintenance
